# Generated by Django 3.2.9 on 2022-01-24 06:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='study_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_i', models.CharField(max_length=30, null=True)),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('FileName', models.FileField(upload_to='static')),
                ('Course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
    ]
