# Generated by Django 3.2.9 on 2022-01-24 06:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ckeditor_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=40, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Thumb', models.ImageField(null=True, upload_to='static/img')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Duration', models.CharField(choices=[('3 mon', '3 MONTH'), ('1 mon', '1 MONTH'), ('6 mon', '6 MONTH')], max_length=100, null=True)),
                ('title', models.CharField(max_length=127)),
                ('sub_title', models.CharField(max_length=127)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('is_official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='courses_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(null=True, upload_to='static/course_img')),
                ('course_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course_no', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=127, null=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='query_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, null=True)),
                ('form_email', models.CharField(max_length=100, null=True)),
                ('form_subject', models.CharField(max_length=100, null=True)),
                ('form_message', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=50, null=True)),
                ('slider_img', models.ImageField(null=True, upload_to='static/slider')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('Number', models.CharField(max_length=12, null=True)),
                ('Aadhaar', models.CharField(max_length=12, null=True)),
                ('Enrollment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), (')', 'Other')], max_length=4, null=True)),
                ('Education', models.CharField(choices=[('10th', 'Secondary education'), ('12th', 'Senior secondary education'), ('Grad', 'Graduation education'), ('P.Grad', 'Post Graduation education')], max_length=50, null=True)),
                ('doc_10', models.FileField(null=True, upload_to='static/docs')),
                ('doc_12', models.FileField(null=True, upload_to='static/docs')),
                ('doc_ug', models.FileField(null=True, upload_to='static/docs')),
                ('doc_pg', models.FileField(null=True, upload_to='static/docs')),
                ('Address', models.TextField(max_length=200, null=True)),
                ('Payment', models.BooleanField(default='False')),
                ('Trm', models.BooleanField(default='False')),
                ('Course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_num', models.PositiveSmallIntegerField(null=True)),
                ('week_num', models.PositiveSmallIntegerField(null=True)),
                ('title', models.CharField(default='', max_length=63, null=True)),
                ('description', ckeditor.fields.RichTextField(default='', null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('vimeo_url', models.URLField(blank=True, null=True)),
                ('bliptv_url', models.URLField(blank=True, null=True)),
                ('preferred_service', models.CharField(choices=[('1', 'YouTube'), ('2', 'Vimeo')], default='1', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course')),
                ('notes', models.ManyToManyField(to='Student.FileUpload')),
            ],
        ),
    ]
